### ISSUE TITLE
Localization - Brazil Portuguese (Português Brasil) <pt-br.cfg>  

### ISSUE THREAD

**Issue by zer0Kerbal** [zer0Kerbal/Halloween#10]
Localization - ![Brazil Portuguese (Português Brasil)][BR] <pt-br.cfg> 

### GameData

- [ ] add pt-br.cfg  

### Translation

- [ ] [![Português Brasil][BR]][BR] [Brazil Portuguese (Português Brasil)][BR] <pt-br.cfg>  

[BR]: https://raw.githubusercontent.com/zer0Kerbal/zer0Kerbal/zed'K/Localization/img/Brazilian-flag-sm.png "Brazil" 

### Update Documentation

- [x]  mod Readme 🔢 
- [x]  releaseNotes.md 🧾 

### GitHub Issues

- [x] assign to zer0Kerbal
- [x] assign projects (user and repo)
- [x] assign label: Localization
- [x] assign label: help-wanted
- [x] assign milestone: Localization - Brazil Portuguese (Português Brasil) <pt-br.cfg>

### Update Social Media

- [x] CurseForge
- [x] CKAN
- [x] Forum
- [x] GitHub
- [x] Patreon
- [x] Reddit
- [x] SpaceDock

### Wiki

- [x] update localization list 
  

[URL:lclztn]: https://github.com/zer0Kerbal/lclztn/blob/master/readme.md "Localization" 
[URL:qs]: https://github.com/zer0Kerbal/lclztn/blob/master/quickstart.md "Quick Start"

**Comment by zer0Kerbal** [comment]
@lemostrash

**Comment by lemostrash** [comment]
@lisias vi um post de mercadinho, então deve ser br, bora fazer junto essa tradução? add discord pra gente só separar

**Comment by zer0Kerbal** [comment]
> @Lisias vi um post de mercadinho, então deve ser br, bora fazer junto essa tradução? add discord pra gente só separar

@lemostrash You are most welcome to just proceed - @lisias has asked me to tag him in all of my addons that need <pt-br.cfg> and when he finds time he said he will work on them (which he usually doesn't have much free ⏳ )

**Comment by zer0Kerbal** [comment]
will release a new version with <pt-br.cfg>

**Comment by zer0Kerbal** [comment]
@lemostrash  just a FYI I will be pushing a release to this addon today. I will merge in this translation when it is completed.
